### ISSUE TITLE
Suggestion: Make new build and update Fdroid

### ISSUE THREAD

**Issue by ConorIA** [MK-42/deskcon-android#5]
Hi there, 

I started a discussion over on FDroid about updating the deskcon-android package with your fork. Discussion here: https://gitlab.com/fdroid/fdroiddata/issues/316#note_2411284

If you are interested, please let the folks over there know. 

Regards,
Conor

**Comment by MK-42** [comment]
Looks interesting. Actually you brought this project back to my brain, I hadn't installed it since i reinstalled my phone and pc and wasn't using it.
Since this is a sparetime project I can't guarantee to provide up to date code always. But if thats no problem i've nothing against it.

At the moment the notifications aren't working, because something in android changed not giving the notifications text to the application. I have to investigate that further.

**Comment by ConorIA** [comment]
It is a great project, with a lot of potential. AFAIK, the only app that offers a similar offering is KDEConnect, but that requires way too much KDE overhead. You seem to be the only person doing anything worthwhile with this codebase, so you are the likely candidate to keep the project going (or kick it back into gear). If you don't have time or interest, it is totally understandable too!

**Comment by MK-42** [comment]
Notifications are fixed again. File Upload is still buggy, I might look into it soon.

**Comment by Burrito-Bazooka** [comment]
I'd also like to see a new release of this.

I use the F-Droid version, but I wonder what would need to happen for it to replace the current one on Google Play. If we can know the cause of the original developer's death, maybe [part of the] Google Play profits can be diverted to a charity related to that cause?

[![](https://api.bountysource.com/badge/issue?issue_id=27502398)](https://www.bountysource.com/issues/27502398-suggestion-make-new-build-and-update-fdroid)
